name: Teste de Construção
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Instalar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Instalar o Newman e o Newman Reporter HTML Extra
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-htmlextra@latest

      - name: Criar Diretório para Resultados
        run: mkdir -p testResults

      - name: Executar a Coleção do Postman
        run: |
          newman run ColecaoTeste.postman_collection.json -n 5 -e workspace.postman_globals.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darktheme > testResults/runreport1.html

      - name: Exibir Detalhes da Execução
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: testResults
