name: Teste de Construção
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  test-api:
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Faz checkout do seu repositório em $GITHUB_WORKSPACE, para que o job possa acessá-lo
      - uses: actions/checkout@v3

      - name: Instalar o Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
    
      - name: Instalar o Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
    
      - name: Criar Diretório para Resultados
        run: mkdir -p testResults

      - name: Executar a Coleção do Postman
        run: |
          newman run MinhaColecao.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darktheme > testResults/runreport1.html

      - name: Exibir Detalhes da Execução
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
