name: Test-Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


    name: Install Node
    uses: actions/setup-node@v1
    with:
      node-version: "12.x"
    
    name: Install Newman
    run: Z
      npm install -g newman
      npm install -g newman-reporter-htmlextra
    
    name: Make Directory for Results
    run: mkdir -p testResults

    name: Run Postman Collection
    run: |
      newman run MinhaColecao.postman_collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darktheme > test Results/runreport1.html

    name: Output the run Details
    uses: actions/upload-artifact@v2
    with:
      name: RunReports
      path: testResults
